version: '3.9'

services:
  nats:
    image: nats:latest
    expose:
      - 4222
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks: ["nats"]

networks:
  nats:
    name: nats      
    